#Gradle properties
org.gradle.jvmargs=-Xmx1024m "-XX:MaxMetaspaceSize=512m"

quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusVersion=3.33.1

javaVersion=21

# PLUGINS
#
openApiGeneratorVersion=7.20.0
#7.20.0
dependencyCheckVersion=12.2.0
detektVersion=1.23.8
dependencyLicenseReportVersion=3.1.1
sonarqubeVersion=7.2.2.6593
dependencyUpdateVersion=0.53.0

# DEPENDENCIES IMPLEMENTATION
#
swaggerAnnotationVersion=1.6.16
jacksonDatabindNullableVersion=0.2.9

# DEPENDENCIES TEST
#
wiremockVersion=3.13.2
mockitoKotlinVersion=6.2.3
assertjCoreVersion=3.27.7

# OTHERS
#
kapt.include.compile.classpath=false
kapt.use.k2=true

group=com.pconil.quarkus.extensions
version=1.0.0